# Generated by Django 5.2.15 on 2026-06-17 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="ai_analysis_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="ai_analysis_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("skipped", "Skipped"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="rule_score",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="score_source",
            field=models.CharField(
                choices=[("rule", "Rule Based"), ("ai", "AI"), ("manual", "Manual")],
                db_index=True,
                default="rule",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["rule_score", "-posted_date"], name="notice_rule_score_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["ai_analysis_status", "-posted_date"],
                name="notice_ai_status_idx",
            ),
        ),
    ]
