# Generated by Django 5.2.15 on 2026-06-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0002_notice_ai_analysis_error_notice_ai_analysis_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "keywords",
                    models.CharField(
                        help_text="Comma-separated keywords. Example: smartfarm, startup, youth farmer",
                        max_length=500,
                    ),
                ),
                ("categories", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agencies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="email_subscriptions",
                        to="notices.agency",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("matched_keywords", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notification_logs",
                        to="notices.notice",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="notices.emailsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emailsubscription",
            index=models.Index(
                fields=["email", "is_active"], name="email_sub_email_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsubscription",
            index=models.Index(
                fields=["is_active", "-created_at"], name="email_sub_active_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailsubscription",
            constraint=models.UniqueConstraint(
                fields=("email", "keywords"), name="uniq_email_subscription_keywords"
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotificationlog",
            index=models.Index(
                fields=["subscription", "status"], name="email_log_sub_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotificationlog",
            index=models.Index(
                fields=["notice", "status"], name="email_log_notice_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotificationlog",
            index=models.Index(fields=["-created_at"], name="email_log_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="emailnotificationlog",
            constraint=models.UniqueConstraint(
                fields=("subscription", "notice"),
                name="uniq_subscription_notice_email_log",
            ),
        ),
    ]
